import img1 from "../src/assets/foods (1).png";
import img2 from "../src/assets/foods (2).png";
import img3 from "../src/assets/foods (3).png";
import img4 from "../src/assets/foods (4).png";
import img5 from "../src/assets/foods (5).png";
import img6 from "../src/assets/foods (6).png";
import img7 from "../src/assets/foods (7).png";
import img8 from "../src/assets/foods (3).png";
import xola from "./assets/xola.svg";
import chol from "./assets/chol.svg";
// galareya uchun export rasimlar

export const foods = [
  {
    id: 0,
    name: "manti",
    massa: 670,
    price: 500,
    img: img1,
    type: "food",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 1,
    name: "salat",
    massa: 270,
    price: 200,
    type: "salat",
    img: img2,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 2,
    name: "fransuscha salat",
    massa: 770,
    price: 700,
    img: img3,
    isTru: false,
    type: "salat",
    productLength: 1,
    type2: "all",
  },
  {
    id: 3,
    name: "goshtli",
    massa: 320,
    price: 2400,
    type: "food",
    img: img4,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 4,
    name: "sho'rva",
    massa: 470,
    price: 800,
    img: img5,
    isTru: false,
    type: "food",
    productLength: 1,
    type2: "all",
  },
  {
    id: 5,
    name: "dimlama",
    massa: 270,
    type: "food",
    price: 600,
    img: img6,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 6,
    name: "anorli salat",
    massa: 400,
    price: 740,
    img: img7,
    type: "salat",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 7,
    name: "italiancha salat",
    massa: 800,
    price: 1840,
    img: img8,
    type: "salat",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 8,
    name: "Perashka",
    massa: 100,
    price: 500,
    img: img1,
    type: "withoutOil",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 9,
    name: "salat",
    massa: 270,
    price: 200,
    img: img2,
    type: "salat",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 10,
    name: "fransuscha salat",
    massa: 770,
    price: 700,
    type: "salat",
    img: img3,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 11,
    name: "goshtli2",
    massa: 320,
    price: 2400,
    type: "food",
    img: img4,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 12,
    name: "sho'rva",
    massa: 470,
    price: 800,
    type: "food",
    img: img5,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 13,
    name: "dimlama",
    massa: 270,
    price: 600,
    img: img6,
    type: "food",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 14,
    name: "anorli salat",
    massa: 400,
    price: 740,
    img: img7,
    type: "salat",
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 15,
    name: "italiancha salat",
    massa: 800,
    price: 1840,
    type: "salat",
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 16,
    name: "CocaCola",
    type: "drink",
    massa: 270,
    price: 200,
    img: img2,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 17,
    name: "Fanta",
    type: "drink",
    massa: 770,
    price: 700,
    img: img3,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 18,
    name: "Pepsi",
    type: "drink",
    massa: 320,
    price: 2400,
    img: img4,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 19,
    name: "sho'rvali salat",
    massa: 700,
    price: 350,
    type: "salat",
    img: img5,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 20,
    name: "kartoshkal salat",
    massa: 900,
    type: "salat",
    price: 500,
    img: img6,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 21,
    name: "anorli salat",
    massa: 1200,
    type: "salat",
    price: 600,
    img: img7,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 22,
    name: "salat",
    type: "salat",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 23,
    name: "Cake",
    type: "desert",
    massa: 770,
    price: 700,
    img: img3,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 24,
    name: "Shrinlik",
    type: "desert",
    massa: 320,
    price: 2400,
    img: img4,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 25,
    name: "Pirog",
    massa: 700,
    price: 350,
    type: "desert",
    img: img5,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 26,
    name: "Shokoladli Kulcha",
    massa: 900,
    type: "desert",
    price: 500,
    img: img6,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 27,
    name: "Bananli To'rt",
    massa: 1200,
    type: "desert",
    price: 600,
    img: img7,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 28,
    name: "Nimadirda",
    type: "desert",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 29,
    name: "7up",
    type: "drink",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 30,
    name: "Maxito",
    type: "drink",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 31,
    name: "Coca Cola",
    type: "drink",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 32,
    name: "Dena",
    type: "drink",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 33,
    name: "Manti",
    type: "withoutOil",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 34,
    name: "Nimdir",
    type: "withoutOil",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 35,
    name: "Niind",
    type: "withoutOil",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
  {
    id: 36,
    name: "adklslkad",
    type: "withoutOil",
    massa: 1000,
    price: 900,
    img: img8,
    isTru: false,
    productLength: 1,
    type2: "all",
  },
];

export const imgs = [
  { title: "this is kavkaz img", img: img1 },
  { title: "this is kavkaz img", img: img2 },
  { title: "this is kavkaz img", img: img3 },
  { title: "this is kavkaz img", img: img4 },
  { title: "this is kavkaz img", img: img5 },
  { title: "this is kavkaz img", img: img6 },
  { title: "this is kavkaz img", img: img7 },
  { title: "this is kavkaz img", img: img8 },
];

export const slideTitles = [
  {
    id: 1,
    img: chol,
    title: "Andrew Garfled",
    text: "Agar restoranimiz sizga maqul bo'lgan bo'lsa oilangiz bilan yoki o'zinggiz kelib dam olib ketishingiz mumkun",
  },
  {
    id: 2,
    img: xola,
    title: "Elithabeth",
    text: ` bizning restoranda har hil taomlar mavjud bo'lib bu tomlar mijozlar
    tomonidan maqulanadi va dunyodagi eng yaxshi shifokorlar tomonidan
    tavsiya etiladi`,
  },
  {
    id: 3,
    img: chol,
    title: "Robert Jr",
    text: "Agar restoranimiz sizga maqul bo'lgan bo'lsa oilangiz bilan yoki o'zinggiz kelib dam olib ketishingiz mumkun",
  },
  {
    id: 4,
    img: chol,
    title: "Chris",
    text: ` bizning restoranda har hil taomlar mavjud bo'lib bu tomlar mijozlar
    tomonidan maqulanadi va dunyodagi eng yaxshi shifokorlar tomonidan
    tavsiya etiladi`,
  },
  {
    id: 5,
    img: chol,
    title: "Tobey Maguire",
    text: "Agar restoranimiz sizga maqul bo'lgan bo'lsa oilangiz bilan yoki o'zinggiz kelib dam olib ketishingiz mumkun",
  },
  {
    id: 6,
    img: chol,
    title: "Harry",
    text: ` bizning restoranda har hil taomlar mavjud bo'lib bu tomlar mijozlar
    tomonidan maqulanadi va dunyodagi eng yaxshi shifokorlar tomonidan
    tavsiya etiladi`,
  },
];
